export const WAITING_FOR_NEW_PLAYERS_OR_START_GAME = 'WAITING_FOR_NEW_PLAYERS_OR_START_GAME';
export const WAITING_FOR_DEAL = 'WAITING_FOR_DEAL';
export const WAITING_FOR_PLAYER_TO_DRAW_OR_KNOCK = 'WAITING_FOR_PLAYER_TO_DRAW_OR_KNOCK';
export const WAITING_FOR_PLAYER_TO_DISCARD = 'WAITING_FOR_PLAYER_TO_DISCARD';
export const THIRTY_ONE = 'THIRTY_ONE';
export const KNOCK_HAND_OVER = 'KNOCK_HAND_OVER';
