export const WAITING_FOR_PLAYER_TO_DRAW_OR_KNOCK = 'WAITING_FOR_PLAYER_TO_DRAW_OR_KNOCK';
export const WAITING_FOR_PLAYER_TO_DISCARD = 'WAITING_FOR_PLAYER_TO_DISCARD';
export const THIRTY_ONE = 'THIRTY_ONE';
export const KNOCK_HAND_OVER = 'KNOCK_HAND_OVER';
